export const SHIPMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  DEVICE_ASSIGNED: "DEVICE_ASSIGNED",
  READY_FOR_DISPATCH: "READY_FOR_DISPATCH",
  IN_TRANSIT: "IN_TRANSIT",
  AT_WAREHOUSE: "AT_WAREHOUSE",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
});

export const ALLOWED_STATUS_TRANSITIONS = Object.freeze({
  [SHIPMENT_STATUS.PENDING]: [SHIPMENT_STATUS.DEVICE_ASSIGNED, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.DEVICE_ASSIGNED]: [SHIPMENT_STATUS.READY_FOR_DISPATCH, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.READY_FOR_DISPATCH]: [SHIPMENT_STATUS.IN_TRANSIT, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.AT_WAREHOUSE, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.AT_WAREHOUSE]: [SHIPMENT_STATUS.DELIVERED],
  [SHIPMENT_STATUS.DELIVERED]: [],
  [SHIPMENT_STATUS.CANCELLED]: [],
});

export const INTEGRITY_STATUS = Object.freeze({
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
  PARTIALLY_VERIFIED: "PARTIALLY_VERIFIED",
  NO_CHECKPOINTS: "NO_CHECKPOINTS",
});

export const BLOCKCHAIN_STATUS = Object.freeze({
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  FAILED: "FAILED",
  MOCK_VERIFIED: "MOCK_VERIFIED",
});
